name: Hello World Workflow

on:
  push:
    branches: [main]
    paths:
      - '01-hello-world/**'

jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run Hello World
        run: python 01-hello-world/main.py
