name: Deploy Static Website

on:
  push:
    branches: [main]
    paths:
      - '02-github-StaticWebsite/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${secrets.TOKEN}
          publish_dir: ./02-github-StaticWebsite