name: Demo Workflow
on:
  push:
    branches: 
      - child-branch

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: List files
        run: ls -l
 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
 
      - name: Run python script
        run: python hello.py  